ditto {
  wot-validation-config {
    ddata {
      pekko-distributed-data {
        gossip-interval = 2s
        log-data-size-exceeding = 100 B
        max-delta-elements = 5
        delta-crdt.max-delta-size = 50
      }
      read-timeout = 5s
      write-timeout = 25s
      subscription-write-consistency = all
      subscription-delay = 2s
      number-of-shards = 5
      subscriber-pool-size = 1
    }
  }
} 